const cardFormFields = [
  {
    label: "Title",
    name: "title",
    type: "text",
    placeholder: "superpharm",
    required: true,
  },
  {
    label: "Subtitle",
    name: "subtitle",
    type: "text",
    placeholder: "Subtitle",
    required: true,
  },
  {
    label: "Description",
    name: "description",
    type: "text",
    placeholder: "Description",
    required: true,
  },
  {
    label: "Phone",
    name: "phone",
    type: "text",
    placeholder: "0541234567",
    required: true,
  },
  {
    label: "Email",
    name: "email",
    type: "email",
    placeholder: "john@doe.com",
    required: true,
  },
  {
    label: "Website",
    name: "web",
    type: "text",
    placeholder: "https://www.example.com",
    required: false,
  },
  {
    label: "Image URL",
    name: "image_url",
    type: "text",
    placeholder: "https://example.com/image.jpg",
    required: false,
  },
  {
    label: "Image Alt",
    name: "image_alt",
    type: "text",
    placeholder: "Image Alt Text",
    required: false,
  },
  {
    label: "State",
    name: "address_state",
    type: "text",
    placeholder: "California",
    required: false,
  },
  {
    label: "Country",
    name: "address_country",
    type: "text",
    placeholder: "USA",
    required: true,
  },
  {
    label: "City",
    name: "address_city",
    type: "text",
    placeholder: "Los Angeles",
    required: true,
  },
  {
    label: "Street",
    name: "address_street",
    type: "text",
    placeholder: "123 Main St",
    required: true,
  },
  {
    label: "House Number",
    name: "address_houseNumber",
    type: "text",
    placeholder: "42",
    required: true,
  },
  {
    label: "ZIP Code",
    name: "address_zip",
    type: "text",
    placeholder: "90001",
    required: false,
  },
];
export default cardFormFields;
