const userFormFields = [
  {
    label: "First Name",
    name: "name_first",
    type: "text",
    placeholder: "John",
    required: true,
  },
  {
    label: "Middle Name",
    name: "name_middle",
    type: "text",
    placeholder: "Middle",
    required: false,
  },
  {
    label: "Last Name",
    name: "name_last",
    type: "text",
    placeholder: "Doe",
    required: true,
  },
  {
    label: "Phone Number",
    name: "phone",
    type: "text",
    placeholder: "0541234567",
    required: true,
  },
  {
    label: "Email Address",
    name: "email",
    type: "email",
    placeholder: "john@doe.com",
    required: true,
  },
  {
    label: "Password",
    name: "password",
    type: "password",
    required: true,
  },
  {
    label: "Image URL",
    name: "image_url",
    type: "text",
    placeholder: "https://example.com/image.jpg",
    required: false,
  },
  {
    label: "Image Alt Text",
    name: "image_alt",
    type: "text",
    placeholder: "An image",
    required: false,
  },
  {
    label: "State",
    name: "address_state",
    type: "text",
    placeholder: "California",
    required: false,
  },
  {
    label: "Country",
    name: "address_country",
    type: "text",
    placeholder: "USA",
    required: true,
  },
  {
    label: "City",
    name: "address_city",
    type: "text",
    placeholder: "Los Angeles",
    required: true,
  },
  {
    label: "Street Address",
    name: "address_street",
    type: "text",
    placeholder: "123 Main St",
    required: true,
  },
  {
    label: "House Number",
    name: "address_houseNumber",
    type: "text",
    placeholder: "42",
    required: true,
  },
  {
    label: "ZIP Code",
    name: "address_zip",
    type: "text",
    placeholder: "90001",
    required: true,
  },
  {
    label: "Business Account",
    name: "isBusiness",
    type: "checkbox",
    required: true,
  },
];

export default userFormFields;
